name: 🏷️ Tree
on:
  workflow_dispatch:

jobs:
          
  prepare-k8s-operator-branch:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      
      - name: "Checkout k8s-operator project"
        uses: actions/checkout@v4
        with:
          repository: kaotoIO/community-operators
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          path: community-operators
          
      - name: "Create, prepare branch and open PR for k8s-operator"
        env:
          BRANCH_NAME: "kaoto-operator-test"
        run: |

          cd community-operators/
          echo ""
          echo "branch        : $BRANCH_NAME"
          echo ""

          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          git remote add upstream https://github.com/k8s-operatorhub/community-operators.git
          git pull --rebase upstream main

          git checkout -b ${BRANCH_NAME}

          cd ../

          tree

